export default {
  statusCodes: [
    { status: 100, description: "Continue" },
    { status: 101, description: "Switching Protocol" },
    { status: 102, description: "Processing" },
    { status: 103, description: "Early Hints" },
    { status: 200, description: "OK" },
    { status: 201, description: "Created" },
    { status: 202, description: "Accepted" },
    { status: 203, description: "Non-Authoritative Information" },
    { status: 204, description: "No Content" },
    { status: 205, description: "Reset Content" },
    { status: 206, description: "Partial Content" },
    { status: 207, description: "Multi-Status" },
    { status: 208, description: "Already Reported" },
    { status: 226, description: "IM Used" },
    { status: 300, description: "Multiple Choice" },
    { status: 301, description: "Moved Permanently" },
    { status: 302, description: "Found" },
    { status: 303, description: "See Other" },
    { status: 304, description: "Not Modified" },
    { status: 305, description: "Use Proxy" },
    { status: 306, description: "unused" },
    { status: 307, description: "Temporary Redirect" },
    { status: 308, description: "Permanent Redirect" },
    { status: 400, description: "Bad Request" },
    { status: 401, description: "Unauthorized" },
    { status: 402, description: "Payment Required" },
    { status: 403, description: "Forbidden" },
    { status: 404, description: "Not Found" },
    { status: 405, description: "Method Not Allowed" },
    { status: 406, description: "Not Acceptable" },
    { status: 407, description: "Proxy Authentication Required" },
    { status: 408, description: "Request Timeout" },
    { status: 409, description: "Conflict" },
    { status: 410, description: "Gone" },
    { status: 411, description: "Length Required" },
    { status: 412, description: "Precondition Failed" },
    { status: 413, description: "Payload Too Large" },
    { status: 414, description: "URI Too Long" },
    { status: 415, description: "Unsupported Media Type" },
    { status: 416, description: "Range Not Satisfiable" },
    { status: 417, description: "Expectation Failed" },
    { status: 418, description: "I'm a teapot" },
    { status: 421, description: "Misdirected Request" },
    { status: 422, description: "Unprocessable Entity" },
    { status: 423, description: "Locked" },
    { status: 424, description: "Failed Dependency" },
    { status: 425, description: "Too Early" },
    { status: 426, description: "Upgrade Required" },
    { status: 428, description: "Precondition Required" },
    { status: 429, description: "Too Many Requests" },
    { status: 431, description: "Request Header Fields Too Large" },
    { status: 451, description: "Unavailable For Legal Reasons" },
    { status: 500, description: "Internal Server Error" },
    { status: 501, description: "Not Implemented" },
    { status: 502, description: "Bad Gateway" },
    { status: 503, description: "Service Unavailable" },
    { status: 504, description: "Gateway Timeout" },
    { status: 505, description: "HTTP Version Not Supported" },
    { status: 506, description: "Variant Also Negotiates" },
    { status: 507, description: "Insufficient Storage" },
    { status: 508, description: "Loop Detected" },
    { status: 510, description: "Not Extended" },
    { status: 511, description: "Network Authentication Required" }
  ],
  statusCodesByCategory() {
    return {
      "Information Responses": this.statusCodes.filter(e => `${e.status}`[0] === '1'),
      "Successful Responses": this.statusCodes.filter(e => `${e.status}`[0] === '2'),
      "Redirection Messages": this.statusCodes.filter(e => `${e.status}`[0] === '3'),
      "Client Error Responses": this.statusCodes.filter(e => `${e.status}`[0] === '4'),
      "Server Error Responses": this.statusCodes.filter(e => `${e.status}`[0] === '5')
    }
  },
  codesOnly() {
    return this.statusCodes.map(e => e.status);
  }
}